export enum FIELD_ERROR {
    NVALID = 'INVALID',
    EMAIL_NOT_ACTIVATED = 'EMAIL_NOT_ACTIVATED',
    PHONE_NOT_ACTIVATED = 'PHONE_NOT_ACTIVATED',
    NOT_DEPOSIT = 'NOT_DEPOSIT',
    EXISTED = 'EXISTED',
    NOT_CODE = 'NOT_CODE'
}
